services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: resume-translator-prod
    ports:
      - "80:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
    env_file:
      - .env
    networks:
      - resume-network
    restart: always
    command: npm start

networks:
  resume-network:
    driver: bridge
